force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLM-{0000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Claim Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <description>US (Validation)</description>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_With_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_With_Tax__c</fullName>
    <description>All (Final Amount)</description>
    <label>Total With Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClaimSelector.cls
public class ClaimSelector implements ISelector {
    public List<Claim__c> getPendingClaims() {
        return [SELECT Id, 
                       Amount__c, 
                       Country_Code__c, 
                       Status__c, 
                       Tax_Amount__c, 
                       Error_Log__c, 
                       State_Code__c,  
                       Tax_ID__c,
                       Total_With_Tax__c
                FROM Claim__c 
                WHERE Status__c = 'Pending'];
    }
}