force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLM-{0000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Claim Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_With_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_With_Tax__c</fullName>
    <description>All (Final Amount)</description>
    <label>Total With Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/USClaimStrategy.cls
public class USClaimStrategy implements IClaimStrategy {
    public void validate(Claim__c claim) {
        if (claim.Amount__c == null || claim.Amount__c <= 0) {
            throw new IllegalArgumentException('Amount is required for US.');
        }
    }

    public void applyTax(Claim__c claim) {
        claim.Tax_Amount__c = claim.Amount__c * 0.07;
    }

    public void calculateTotal(Claim__c claim) {

        Decimal amount = claim.Amount__c != null ? claim.Amount__c : 0;
        Decimal tax = claim.Tax_Amount__c != null ? claim.Tax_Amount__c : 0;
        
        claim.Total_With_Tax__c = amount + tax;
    }
}